### ISSUE TITLE
Add Phyx LANA TNY board

### ISSUE THREAD

**Issue by Brubacker** [adafruit/awesome-qt-py#2]
The Phyx LANA TNY board, a [WCH CH32V203](https://www.wch-ic.com/products/CH32V203.html) based Qt-Py / XIAO compatible microcontroller board with a WS2812 compatible RGB LED and a Stemma QT I2C Port on board. It has an extra output for the WS2812 LED data and additional IO pins on the 1.27mm pitch SMD pads.

![image](https://github.com/adafruit/awesome-qt-py/assets/950047/716eadee-67a2-462b-90d4-e89dbb6675a9)

No CircuitPython yet, no Wireless, but it does have Arduino compatibility.

Source files : https://github.com/phyx-be/LANA_TNY
Shop link : https://lectronz.com/products/lana-tny

**Comment by TheKitty** [comment]
Thank you, added.
